In [10]:
from tqdm.auto import tqdm
import os
import glob
import numpy as np

# 영상 저장 경로 (안에 카테고리별로 영상 폴더를 만들어줘야 함)
root_path = "D:/newGTAVideo"
folders = os.listdir(root_path)
print(folders)
# 피처 저장 경로
save_path = "D:/newGTAI3D"
os.makedirs(save_path, exist_ok=True)

['newGTAKnife', 'newGTANormal1', 'newGTANormal2', 'newGTAShooting']


In [11]:
from models.i3d.extract_i3d import ExtractI3D
from utils.utils import build_cfg_path
from omegaconf import OmegaConf
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

feature_type = 'i3d'

args = OmegaConf.load(build_cfg_path(feature_type))

cuda


In [ ]:
for folder in tqdm(folders):
  print(folder)
  video_path = glob.glob(os.path.join(os.path.join(root_path, folder), "*.mp4"))
  args.video_paths = video_path
  extractor = ExtractI3D(args)
  
  os.makedirs(os.path.join(save_path, folder), exist_ok=True)
  
  for video in tqdm(video_path):
    npy_feature = extractor.extract(video)['rgb'].squeeze(2)
    print(npy_feature.shape)
    for i in range(10):
      np.save(os.path.join(os.path.join(save_path, folder), video.split('\\')[-1].split('.')[0] + "__" + str(i) + ".npy".format(i)), npy_feature[:, i, :])

In [13]:
print(np.load("D:/newGTAI3D/newGTAKnife/0000_view1__0.npy"))

[[0.12597656 0.26799196 0.08882554 ... 0.39174211 0.09951477 0.11874004]
 [0.29615191 0.35302073 0.23057556 ... 0.38228345 0.10528148 0.10059863]
 [0.2805095  0.34091818 0.24267031 ... 0.43592051 0.08626223 0.09277886]
 ...
 [0.26683733 0.3691588  0.23583543 ... 0.32647935 0.14614084 0.07244483]
 [0.27201962 0.36510339 0.22953051 ... 0.46086296 0.13892935 0.08056269]
 [0.27249312 0.36295637 0.23074858 ... 0.47390687 0.16710839 0.07435413]]
